### PR TITLE
Windows 10 SDK November release

### PR DESCRIPTION
**Pull request by jberezanski**
This PR upgrades the Windows 10 SDK to the November release (Windows 10 build 10586). It also adds a few diagnostic improvements I found useful when rolling the SDK out to a couple dozen machines.

The catch is that the November SDK release bumps the version number to 10.1.10586.15, making the package id (windows-sdk-10.0) no longer appropriate. To address this, the PR introduces a new package id, windows-sdk-10, intended to carry this and all future upgrades to the SDK. The old package id is made dependent on the new one, so that existing users can upgrade easily.

### CODE REVIEW

**Comment by jberezanski** [comment]
Unfortunately, upon a more thorough examination, I saw that the upgrade is _mostly_ in-place, but not entirely:
- the SDK installs to the same directory (C:\Program Files (x86)\Windows Kits\10) and
- tools, such as debuggers, get in-place upgraded to 10.0.10586.15,
but:
- both SDKs install separate sets of C include and lib files (10.0.10240.0 and 10.0.10586.0 respectively) and
- both SDKs exist as separate entries in Programs and Features (at first I thought it was a bug).

I'm not so sure now what the best packaging strategy should be. On the one hand, both SDKs should be installable side-by-side, so that C/C++ developers could target the specific Windows 10 release. On the other, most folks would benefit from being able to simply upgrade the package to get the latest tools.

How about this:
1) windows-sdk-10.0 is left intact,
2) windows-sdk-10.1 is added and does what windows-sdk-10 does currently in this PR (i.e. installs the November SDK),
3) windows-sdk-10 is added - an upgradeable metapackage, which does not install anything by itself, but takes a dependency on the latest windows-sdk-10.x package, so it is upgradeable.

What do you think?

**Comment by patrickmaurer** [comment]
Sounds like the best available option given the versioning issues around these SDKs.

Could you adjust this PR to reflect your suggested changes? Thanks!

**Comment by jberezanski** [comment]
Done.
I've deliberately added two versions of windows-sdk-10, with the intention for both of them to be published on chocolatey.org, in order to make the packaging strategy obvious to anyone examining the package page.

**Comment by patrickmaurer** [comment]
Thanks again! I finally came around to merge the PR and upload to chocolatey.org.

**Pull request merged**
